src/config/routes.rb
Rails.application.routes.draw do
  resources :codes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

src/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

src/app/models/code.rb
class Code < ApplicationRecord
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

src/app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: %i[ show edit update destroy ]

  # GET /codes or /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1 or /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes or /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to code_url(@code), notice: "Code was successfully created." }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1 or /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to code_url(@code), notice: "Code was successfully updated." }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1 or /codes/1.json
  def destroy
    @code.destroy

    respond_to do |format|
      format.html { redirect_to codes_url, notice: "Code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def code_params
      params.require(:code).permit(:value)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/codes_helper.rb
module CodesHelper
end

src/app/views/codes/_code.html.erb
<div id="<%= dom_id code %>">
  <p>
    <strong>Value:</strong>
    <%= code.value %>
  </p>

</div>

src/app/views/codes/_form.html.erb
<%= form_with(model: code) do |form| %>
  <% if code.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
        <% code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

src/app/views/codes/edit.html.erb
<h1>Editing code</h1>

<%= render "form", code: @code %>

<br>

<div>
  <%= link_to "Show this code", @code %> |
  <%= link_to "Back to codes", codes_path %>
</div>

src/app/views/codes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Codes</h1>

<div id="codes">
  <% @codes.each do |code| %>
    <%= render code %>
    <p>
      <%= link_to "Show this code", code %>
    </p>
  <% end %>
</div>

<%= link_to "New code", new_code_path %>

src/app/views/codes/new.html.erb
<h1>New code</h1>

<%= render "form", code: @code %>

<br>

<div>
  <%= link_to "Back to codes", codes_path %>
</div>

src/app/views/codes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @code %>

<div>
  <%= link_to "Edit this code", edit_code_path(@code) %> |
  <%= link_to "Back to codes", codes_path %>

  <%= button_to "Destroy this code", @code, method: :delete %>
</div>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arena Codes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>